### ISSUE TITLE
Module translation: Introduction and Table of Contents

### ISSUE THREAD

**Issue by giocodes** [giocodes/modern-js-cheatsheet#1]
I've completed the translation of 
* Introduction
* Table of Contents

I would like some feedback to confirm that everything looks good.

**Comment by GMaiolo** [comment]
A couple of things: 

- I prefer using MDN as standard, and [they use the word Array instead of *Arreglo*](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Array), and also [map](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Array/map), [reduce](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Array/reduce), [filter](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Array/filter). Translating the method or type itself seems to be pretty misleading (*mapa* instead of *map* is the best example I can think of) because we would end up saying *Cuerda* instead of String.

- There are some things left unclear in spanish, for example the section "Promise handlers usage" is translated as "Prometa el uso de manejadores" and the literal translation would be "Uso del ejecutor de las promesas", and even then I'd stretch to use _ejecutor_ here and lean for _handler_ itself.

- Section "Object property shorthand" is translated as "Propiedad abreviada de propiedad" which is pretty confusing by itself, it should be "Abreviación para propiedad de objeto".

These are just a couple of things I noticed giving a quick glance and there is no current pull request opened for this.

**Comment by giocodes** [comment]
@GMaiolo thanks for the feedback. I've created a PR so you can add inline comments if necessary.

**Comment by giocodes** [comment]
@GMaiolo did you had a chance to look at this? Is it good to go?
